version: "3.8"

services:
  web:
    image: node:16-alpine
    command: sh -c "npm run build && node .svelte-kit/build/app.js"
    ports:
      - "3000:3000"
    working_dir: /app
    volumes:
      - ./:/app

  database:
    image: postgres:14-alpine
    restart: always
    volumes:
      - todo-mysql-data:/var/lib/mysql
    environment:
      POSTGRES_DB: $PGDATABASE
      POSTGRES_USER: $PGUSER
      POSTGRES_PASSWORD: $PGPASSWORD

volumes:
  todo-mysql-data:
