version: "3.8"

services:
  svelteApp:
    image: node:16-alpine
    command: sh -c "npm run build && node .svelte-kit/build/app.js"
    ports:
      - "3000:3000"
    working_dir: /app
    volumes:
      - ./:/app
    environment:
      PGHOST: localhost
      PGDATABASE: wishlist
      PGUSER: wishlituser
      PGPASSWORD: wishlistpassword
      PGPORT: 5432

  postgresDb:
    image: postgres:14-alpine
    restart: always
    volumes:
      - todo-mysql-data:/var/lib/mysql
    environment:
      POSTGRES_DB: wishlist
      POSTGRES_USER: wishlituser
      POSTGRES_PASSWORD: wishlistpassword

volumes:
  todo-mysql-data:
